package com.totemsoft.screenlookcount.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.totemsoft.screenlookcount.db.DayLook;

import com.totemsoft.screenlookcount.db.DayLookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayLookDaoConfig;

    private final DayLookDao dayLookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayLookDaoConfig = daoConfigMap.get(DayLookDao.class).clone();
        dayLookDaoConfig.initIdentityScope(type);

        dayLookDao = new DayLookDao(dayLookDaoConfig, this);

        registerDao(DayLook.class, dayLookDao);
    }
    
    public void clear() {
        dayLookDaoConfig.getIdentityScope().clear();
    }

    public DayLookDao getDayLookDao() {
        return dayLookDao;
    }

}
