package com.totemsoft.screenlookcount.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DAY_LOOK".
 */
public class DayLook {

    private Long id;
    /** Not-null value. */
    private String date;
    private Integer screenon;
    private Integer screenoff;
    private Integer screenunlock;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DayLook() {
    }

    public DayLook(Long id) {
        this.id = id;
    }

    public DayLook(Long id, String date, Integer screenon, Integer screenoff, Integer screenunlock) {
        this.id = id;
        this.date = date;
        this.screenon = screenon;
        this.screenoff = screenoff;
        this.screenunlock = screenunlock;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getScreenon() {
        return screenon;
    }

    public void setScreenon(Integer screenon) {
        this.screenon = screenon;
    }

    public Integer getScreenoff() {
        return screenoff;
    }

    public void setScreenoff(Integer screenoff) {
        this.screenoff = screenoff;
    }

    public Integer getScreenunlock() {
        return screenunlock;
    }

    public void setScreenunlock(Integer screenunlock) {
        this.screenunlock = screenunlock;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
